# Site settings
minimal_mistakes_skin : mint
title                 : Andrew Yew
title_separator       : ""
subtitle              : Data Scientist
email                 : andrewyewcy@gmail.com
description           : >- # this means to ignore newlines until "baseurl:"
  Portfolio of Andrew Yew, a data scientist.
name                  : Andrew Yew
linkedin_username     : andrewyewcy
github_username       : andrewyewcy
words_per_minute      : 200
search                : true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
timezone: America/Toronto # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones\
paginate: 5 # amount of posts to show
paginate_path: /page:num/


include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Andrew Yew"
  avatar : "/assets/images/Andrew_Yew.jpg"
  bio    : "With experience in developing data processing and machine learning solutions  for numerical and textual data in the manufacturing and technology fields, let me help you identify and realize technical data solutions for your business."
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "http://linkedin.com/in/andrewyewcy"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "http://github.com/andrewyewcy"
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "http://linkedin.com/in/andrewyewcy"    
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "http://github.com/andrewyewcy"
collections:
  projects:
    output: true
    permalink: /:collection/:path/
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: true
      toc: true
      toc_label: "Table of Contents"
      toc_icon: "cog"
      toc_sticky: true      
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
      share: true



category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

