# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Full Stack Data Science
email: andrewyewcy@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi there, I'm Andrew and this is my journey through the nooks and crannies of data science.
#twitter_username: username
linkedin_username: andrewyewcy
github_username: andrewyewcy
minimal_mistakes_skin: mint
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Andrew Yew"
  avatar : "/assets/images/Andrew_Yew.jpg"
  bio    : "Business Analyst turned Data Scientist, I am interested in machine learning operations and unstuctured data processing, such as texts and images. Join me as I explore the nooks and crannies of data science from data engineering to model deployment on cloud services like AWS."
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "http://linkedin.com/in/andrewyewcy"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "http://github.com/andrewyewcy"
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "http://linkedin.com/in/andrewyewcy"    
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "http://github.com/andrewyewcy"
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      toc_label: "Table of Contents"
      toc_icon: "cog"
      toc_sticky: true      
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true



category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

